### ISSUE TITLE
Dont see the msg of fly activated

### ISSUE THREAD

**Issue by UnEnanoMas** [AGTHARN/FlyPE#11]
Since pocketmine changed the version, every time I use / fly a black line appears in the chat but no message appears, the fly is activated but not put by the chat

**Comment by AGTHARN** [comment]
Hey, thanks for letting me know. I will try to fix it after I have confirmed that this is a bug.

**Comment by AGTHARN** [comment]
Hey, i've tested the latest version and everything seems fine. Please check if your config is updated and has the customizable messages.

**Comment by UnEnanoMas** [comment]
It was an error of mine, the plugin updated it in the latest version, but the config did not change, so that was why, I had to delete it and now it works
