### ISSUE TITLE
[Suggestion] Temporal Flight Command

### ISSUE THREAD

**Issue by BLAST1718** [AGTHARN/FlyPE#24]
make it so u can do /tempfly (player) (time)

**Comment by AGTHARN** [comment]
It has been planned and is currently being worked on with other features in #22.

**Comment by BLAST1718** [comment]
What's the command for fly coupon on #22

**Comment by BLAST1718** [comment]
What's the command for fly coupon on #22

**Comment by BLAST1718** [comment]
What's the command for fly coupon on #22

**Comment by AGTHARN** [comment]
It is **currently being worked on** and has yet to be updated.

**Comment by BLAST1718** [comment]
so how can i get flighy coupon on #22

**Comment by BLAST1718** [comment]
?

**Comment by AGTHARN** [comment]
Hello! Sorry it took a while, I was quite busy. I have finished your suggestion by separating the flight command into subcommands. Feel free to test it here by [Downloading](https://poggit.pmmp.io/r/116558/FlyPE_pr-101.phar) (PR-101). This is not to be used for production servers yet so you may expect issues.

You will see the commands auto-fill when you type /fly.

**Comment by BLAST1718** [comment]
Ah k 😊
Thanks

**Comment by BLAST1718** [comment]
> Hello! Sorry it took a while, I was quite busy. I have finished your suggestion by separating the flight command into subcommands. Feel free to test it here by [Downloading](https://poggit.pmmp.io/r/116558/FlyPE_pr-101.phar) (PR-101). This is not to be used for production servers yet so you may expect issues.
> 
> You will see the commands auto-fill when you type /fly.

How about make a temp flight coupon
