### ISSUE TITLE
If you hit a player, the fly is activated

### ISSUE THREAD

**Issue by UnEnanoMas** [AGTHARN/FlyPE#26]
I have hit my players and the fly is transferred to them when I hit them, please correct that

Dev 84

**Comment by UnEnanoMas** [comment]
https://streamable.com/mn6s2q (What the player who hits the player sees)

![Screenshot_2021-05-05-13-01-24-32_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/63286108/117131890-5a867300-ada2-11eb-83f4-ac37f2206c88.jpeg) (what the player they hit sees)

**Comment by AGTHARN** [comment]
Hello! Thanks for reporting this bug! May you help me in downloading the latest dev version and letting me know if it fixes the issue?

**Comment by UnEnanoMas** [comment]
![image](https://user-images.githubusercontent.com/63286108/117300501-e4553f80-ae79-11eb-8d9f-ddbb3a1b80e1.png)

Yes it has been corrected, but now there is another error.

If the player executes the / fly command and is on cooldown, the / fly is not deactivated, he has to wait for the seconds that he sets, but if he executes the command again after those seconds, it appears as "fly on" when it was already on

I think the problem is that the plugin does not detect that if the player has the fly activated and the cooldown message appears, the action should be canceled, so that when the player writes after the cooldown / fly the message of "fly off"

**Comment by AGTHARN** [comment]
That's a very weird behaviour, but I don't quite get it. Is it fine if you could send a video of the bug please? Thank you!

**Comment by UnEnanoMas** [comment]
https://streamable.com/ty9ayi

**Comment by UnEnanoMas** [comment]
What I mean, that when the player executes the / fly command and the message of "the command is on cool down" appears then when using the / fly, it tells the player that the flight has been turned on when it was previously on

**Comment by UnEnanoMas** [comment]
It is as if in the cooldown message it executes the command "/ fly off" but without denying it, so that the next time when using / fly it means that it is on.

I don't know if I have explained myself well xd

**Comment by AGTHARN** [comment]
I get what you mean. However, the cooldown applies for both turning on and turning off the flight. After the second time when it shows it turns on again, is your flight still toggled on? And what happens when you do it again for the third time? (does it happen again or?)

**Comment by UnEnanoMas** [comment]
I explain with an example:

I use / fly and the flight is activated

I run / fly again after a few seconds and I get the "cooldown" message (Then it simulates that the fly has been deactivated and denies the "fly off" message but the flight does not deactivate it.

I use / fly again after passing the cooldown and I get "fly on" but the flight was already activated.

** If you use / fly twice when the cooldown is active, the fly will be deactivated **

Want a video?

**Comment by AGTHARN** [comment]
I can't seem to reproduce this issue. Can we talk on Discord instead so we can have a better communication? AGTHARN#0996

**Comment by UnEnanoMas** [comment]
I have already sent to you

**Comment by UnEnanoMas** [comment]
Fixed issue in dev # 87
